### ISSUE TITLE
Cacti Versions 1.1.36 - Hmib 3.1

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_hmib#10]
I have this error when i try to get data with "verbose query":
--> Host MIB - Summary Application Stats
Total: 0.000000, Delta: 0.000000, Running data query [8].
Total: 0.000000, Delta: 0.000000, Found type = '6' [Script Query - Script Server].
Total: 0.010000, Delta: 0.010000, Found data query XML file at '/usr/share/cacti/plugins/hmib/templates/resource/script_server/hmib_sum_apps.xml'
Total: 0.010000, Delta: 0.000000, XML file parsed ok.
Total: 0.010000, Delta: 0.000000, <arg_num_indexes> missing in XML file, 'Index Count Changed' not supported
Total: 0.680000, Delta: 0.660000, Executing script for list of indexes '"/usr/bin/php" -q /usr/share/cacti/plugins/hmib/templates/scripts/ss_hmib_sum_apps.php '' 'index'', Index Count: 0

No problem if i use:
--> Host MIB - Get Mounted Partitions 
Total: 0.000000, Delta: 0.000000, Running data query [4].
Total: 0.000000, Delta: 0.000000, Found type = '6' [Script Query - Script Server].
Total: 0.010000, Delta: 0.010000, Found data query XML file at '/usr/share/cacti/resource/script_server/host_disk.xml'
Total: 0.010000, Delta: 0.000000, XML file parsed ok.
Total: 0.800000, Delta: 0.790000, Executing script for num of  indexes '"/usr/bin/php" -q /usr/share/cacti/scripts/ss_host_disk.php  '10.31.184.254' '12' '2:161:600:3:32:fwrosoc::::::' 'num_indexes''
Total: 0.800000, Delta: 0.000000, Found number of indexes: 11
Total: 1.550000, Delta: 0.760000, Executing script for list of  indexes '"/usr/bin/php" -q /usr/share/cacti/scripts/ss_host_disk.php  '10.31.184.254' '12' '2:161:600:3:32:fwrosoc::::::' 'index'', Index  Count: 11

Do you have suggestions?

thanks a lot.

**Comment by netniV** [comment]
It suggests, the hmib_sum_apps doesn't include an index count field (arg_num_indexes) in the XML file, and therefore you cannot use Index Count as a method of reindexing, you must use on of the others.
