### ISSUE TITLE
help

### ISSUE THREAD

**Issue by flying-bigbird** [Cacti/plugin_hmib#14]
hmib can not be chanslated,mo file and po file are copy from github,why？help！！

**Comment by netniV** [comment]
If you want to help out with Translations, we are trialling a new service.  Please email weblate@cacti.net for more information.

**Comment by flying-bigbird** [comment]
po file:../locals/po/zh-CN.po  mo file: ../locales/LC_MESSAGES/zh-CN.mo
both file are download from github,Can you tell me how  cacti get the po file?

**Comment by netniV** [comment]
the file `include/global_languages.php` helps sort that out.
