### ISSUE TITLE
Why cacti plugin hmib can not translated ?

### ISSUE THREAD

**Issue by flying-bigbird** [Cacti/plugin_hmib#16]
Cacti plugins for monitor、mactrack、netflow、syslog  can translate very well but plugin hmib can not translated .The method is the same.I would like to know how cacti extracts the Po file?
po file path:/hmib/locales/po/ chinese_china_simplified.po
mo file path:/hmib/locales/LC_MESSAGES/chinese_china_simplified.mo
Both files are download from Github,like other plugin ,No error!

I found when i put the hmib translate file (mo file) to the /var/www/html/local/LC_MESSAGES ,The plugin hmib can translate,but cacti core can not translate ! WHY??

**Comment by flying-bigbird** [comment]
My cacti version is 1.1.37。

**Comment by netniV** [comment]
You've asked this question in the cacti core repo too, and I've answered it there so I'm going to close this one now.
