### ISSUE TITLE
hmib system types

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_hmib#17]
Question:
HMIB used to detect many different system types. I just reinstalled and notice that it detect very little now. Did the types get changed? I only see 14 very old and specific types. 

        db_execute("INSERT INTO `plugin_hmib_hrSystemTypes` VALUES
                (1,'.1.3.6.1.4.1.311.1.1.3.1.1',  'Version 6.1','Windows 7','7'),
                (2,'.1.3.6.1.4.1.311.1.1.3.1.2',  'Version 6.1','Windows 2008 Server','2008'),
                (3,'.1.3.6.1.4.1.311.1.1.3.1.3',  'Version 6.1','Windows 2008 Domain Contr','2008'),
                (4,'.1.3',                        'Linux NAS%armv5tejl','DNS-321',''),
                (5,'.1.3.6.1.4.1.2.3.1.2.1.1.3',  'IBM%AIX%05.03','AIX','5.3'),
                (6,'.1.3.6.1.4.1.8072.3.2.10',    'Linux%2.6.16.21-0.8%','SUSE','10.2'),
                (7,'.1.3.6.1.4.1.311.1.1.3.1.1',  'EM64T%Windows Version 5.2','Windows XP x64','5.2'),
                (8,'.1.3.6.1.4.1.311.1.1.3.1.1',  'Windows 2000 Version 5.0','Windows 2000','5.0'),
                (9,'.1.3.6.1.4.1.311.1.1.3.1.1',  'Windows 2000 Version 5.1','Windows XP','5.1'),
                (10,'.1.3.6.1.4.1.8072.3.2.10',   'Linux%2.6.16.60','SUSE','9.0'),
                (11,'.1.3.6.1.4.1.311.1.1.3.1.2', 'Windows 2000 Version 5.0','Windows 2000 Server','2000'),
                (12,'.1.3.6.1.4.1.311.1.1.3.1.2', 'Windows 2000 Version 5.1','Windows 2000 Server','2000'),
                (13,'.1.3.6.1.4.1.311.1.1.3.1.3', 'Windows Version 5.2','Windows 2003 DC','2003'),
                (14,'.1.3.6.1.4.1.311.1.1.3.1.2', 'Windows Version 5.2','Windows 2003 Server','2003');");

**Comment by jdcoats** [comment]
I have manually added what I wanted for today, I guess I was just thinking that there were more defaults available, its been a while since I used it.

**Comment by netniV** [comment]
Submit a PR with updated defaults if you have some :)

**Comment by jdcoats** [comment]
I will when I get them all done. I found another issue though and its holding me up finding and creating the last few device os types. The default "Unknown" OS type cant be filtered on. You can click the link but it just shows all devices and on the devices tab you cant filter for type "Unknown"

**Comment by jdcoats** [comment]
Close issue as pull request created. I will open a new issue related to not being able to filter on "Unknown"
