### ISSUE TITLE
Device import failure

### ISSUE THREAD

**Issue by WirthmU** [Cacti/plugin_hmib#20]
I could load the plugin but when I want to import the device file "Host_Mib_Summary_Device.xml.gz" I get the following errors:
XML parse error.
XML: Cacti version does not exist

hmib is version 3.1 and cacti is 1.2.8 running on ubuntu.

Any help to this?

**Comment by WirthmU** [comment]
Solved it using the cli import_package.php

**Comment by netniV** [comment]
Yeah, we really should have the gui detect that you are trying to run a package import rather than basic template import.
