### ISSUE TITLE
Device Type Unknown does not filter

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_hmib#23]
You should be able to filter for Type "Unknown" but this is not working. If you go to the HMIB Summary page and select the device count for Unknown it should display only the unknown devices however it displays all devices. If you go to the HMIB Devices tab you should be able to filter for OS Type Unknown however it is not an available selection.
![Unknown](https://user-images.githubusercontent.com/42470924/76417350-1c92e800-6373-11ea-81c6-5c6ff6ab686b.png)

**Comment by jdcoats** [comment]
to work around the above issue, User should be able to select OS Type "Unknown" to show the 14 unknown devices but cannot.
![Unknown2](https://user-images.githubusercontent.com/42470924/76417570-785d7100-6373-11ea-8201-90c4d87c0dca.png)

**Comment by jdcoats** [comment]
Another broken filter in hmib. In processes, If you search for a process and find results. Clicking on the next page of results, clears the search and shows all processes.
![filter](https://user-images.githubusercontent.com/42470924/76424999-641f7100-637f-11ea-8dfb-ce54df47847f.png)

**Comment by TheWitness** [comment]
This should be fixed.

**Comment by jdcoats** [comment]
perfect! Thanks!
