### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_hmib#29]
I've had HMIB poller disabled a while and just enabled to find the below message replicated quite a bit.
```
2021/12/29 16:33:00 - ERROR PHP DEPRECATED in Plugin 'hmib': Invalid characters passed for attempted conversion, these have been ignored in file: /var/www/localhost/htdocs/cacti/plugins/hmib/snmp.php on line: 459
2021/12/29 16:33:00 - CMDPHP PHP ERROR Backtrace: (/plugins/hmib/poller_hmib.php[139]:checkHost(), /plugins/hmib/poller_hmib.php[577]:collect_hrStorage(), /plugins/hmib/poller_hmib.php[959]:collectHostIndexedOid(), /plugins/hmib/poller_hmib.php[715]:cacti_snmp_walk(), /plugins/hmib/snmp.php[413]:format_snmp_string(), /plugins/hmib/snmp.php[459]:hexdec(), CactiErrorHandler())
```

**Comment by TheWitness** [comment]
@jdcoats, if this is happening all the time, I need you to stuff the following right before $newstr

```php
cacti_log(sprintf("Char %s, Hexdec %s", $p, hexdec($p)));
```

**Comment by jdcoats** [comment]
I keep Hmib disabled most of the time because it appears to be such a resource hog for me, I will re-enable and test more once I get a stable baseline after the latest updates of cacti and weathermap

**Comment by jdcoats** [comment]
I have not seen this one again since.

**Comment by TheWitness** [comment]
Let's close this one.  If it pops back up again, open a new ticket and provide a backtrace.
