### ISSUE TITLE
Unknown devices

### ISSUE THREAD

**Issue by bonj1987** [Cacti/plugin_hmib#31]
not sure if its a bug per se.. but in my environment i have a bunch of F5 devices. i have templates for them and I am graphing a bunch of stuff, but HMIB sees them as "unknown" device types, same with my printers.

**Comment by MROSSFTEK** [comment]
Im having an issue where my printers are also not able to be detected properly by HMIB plug in.. where do i change this? do i need device specific MIB files saved into the cacti folder structure? are there tables I need to change? 
![hmib1](https://github.com/Cacti/plugin_hmib/assets/141238662/648b7183-37b1-47b5-95f6-f9bb844c2c54)

**Comment by TheWitness** [comment]
You have to go to the device types interface and add them.  There is a scan function to pick up the unknowns, and then you simply edit and save the names.

**Comment by MROSSFTEK** [comment]
do you mean OS TYPES?
![hmib2](https://github.com/Cacti/plugin_hmib/assets/141238662/9f330381-f63e-4e02-b1ec-251e326873ce)

**Comment by MROSSFTEK** [comment]
ok  i follow you now.. add it to host types, do a rescan, and it should find it.. ok.
so.. ive been able to make them, successfully with some hit and misses.. 
case of misses.. i have quite a few HP printers in my environment. i have those devices listed in cacti, and im graphing them.. but.. hmib is not finding all of them.. when ido an SNMP walk against them, it appears im finding the same object ID and the same OS "versions" .. with some minor differences.. but they all start with "HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT" after that text, they all differ, such as ",JD149,EEPROM JDI23900047,CIDATE 02/15/2021" and ",JD102,EEPROM V.43.11,CIDATE 02/20/2012". i thought maybe starting them all wtih the HP ETHERNET MULTI... line would pick them all up, but it only picks up ONE of them. the OID for the HP printers all appear to be the same.. ".1.3.6.1.4.1.11.2.3.9.1". but i cant get it to find ALL them via HMIB... suggestions?

**Comment by MROSSFTEK** [comment]
been having a devil of a time with HP printers.. 
Now, mind you they all graph, pull data just fine.. but with HMIB, Host types.. only picks up ONE of these.. 

systemID oid .1.3.6.1.4.1.11.2.3.9.1
SystemDesc Match that IS detected
HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT   -- this is the ONLY HP printer hostmib is picking up

All these others share the same SystemID oid as above, but the SystemDesc Match differ and HMIB does not pick these up
HP ETHERNET MULTI-ENVIRONMENT,SN:CNF8F4KC75,FN:P969482,SVCID:23266,PID:HP LaserJet M1536dnf MFP
HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT,JD102,EEPROM V.43.11,CIDATE 02/20/2012
HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT,JD121,EEPROM V.30.31,CIDATE 06/17/2005
HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT,JD102,EEPROM V.43.11,CIDATE 02/20/2012
HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT,JD102,EEPROM V.43.11,CIDATE 02/20/2012
HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT,JD102,EEPROM V.43.11,CIDATE 02/20/2012

**Comment by TheWitness** [comment]
It's been a while since I wrote it.  Is it possible to only use the sysobectid?

**Comment by MROSSFTEK** [comment]
ive tried with just the sysobjectid... same results. ive tried with just the systemdesc match, same results.
to get my watchguards to be discovered i had to set the OS to M370 and the  systemdesc to M370 with no OID for the systemobjectID.

**Comment by TheWitness** [comment]
Interesting.  I tried 'auto-discovering' setting up a fresh install and encountered issues myself.

**Comment by MROSSFTEK** [comment]
just checking to see if there were any updates?

**Comment by TheWitness** [comment]
Sorry, super busy at the office and now a quick vacation.  Thanks for reminding me though.

**Comment by TheWitness** [comment]
Back working again.  Getting a new release ready to go.

**Comment by TheWitness** [comment]
For the various match strings, you can just use for example for sysDescr Match of "JETDIRECT" and that'll pick up all of them.  You were making it harder than it had to be.

**Comment by TheWitness** [comment]
I'm going to close.  If you still have issues, let me know.
