### ISSUE TITLE
Import Host Template Errors

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_hmib#4]
This is with latest git for Cacti 1.0.0 and trying to import the cacti_host_template_host_mib_summary_device.xml file

CDEF

[success] [new] 
[success] [unchanged] 
GPRINT Preset

[success] [unchanged] 
[success] [unchanged] 
[success] [new] 
Data Input Method

[success] [unchanged] 
Data Template

**[fail] [new] 
[fail] [new] 
[fail] [new] 
[fail] [new] 
[fail] [new] 
[fail] [new] 
[fail] [new] 
Graph Template**

**[fail] [new]** 
[success] [new] 
[success] [new] 
[success] [new] 
[success] [new] 
[success] [new] 
[success] [new] 
Data Query

[success] [new] 
[success] [new] 
Device Template

[success] [new] 
Data Source Profile

[success] [new]

**Comment by cigamit** [comment]
Please use the package included in the latest Cacti 1.0 installer location and the package in install/templates.  The information included in this plugin will be removed in a favor of the new package.

There is an 'install_package.php' cli script for installing packages.

**Comment by cigamit** [comment]
I'm assuming that you have found the package and have installed it.
