### ISSUE TITLE
WARNING: You need to import your Host MIB Host Template

### ISSUE THREAD

**Issue by hackdefendr** [Cacti/plugin_hmib#6]
Hi

I have installed the plugin per the README and am still seeing this warning

WARNING: You need to import your Host MIB Host Template to view Graphs. See the README for more information.

What Host MIB Template is this talking about?

**Comment by peter-thoenen** [comment]
I believe he is talking about the "Host_Mib_Summary_Device.xml.gz" which you need to download and extract and then import as an native xml via the Cacti->Import Template function.

OFC after you do that it fails :) .. i.e. it imports with no errrors but also no successes (normally an import lists a bunch of items it imported)

**Comment by cigamit** [comment]
Sorry, the doco is a little out of date.  There is a lot to do and only so much time in a day.  You need to use the CLI script called "import_package.php" to import that tar.gz file.  Then you will have everything you need to start graphing.  If you feel so inclined, create a pull request with your edits to the README.md file.

**Comment by hackdefendr** [comment]
Thanks cigamit.

**Comment by peter-thoenen** [comment]
I have no problem updating the documentation but I feel like I'm missing something:

[root@prh-ls-mon cli]# php import_package.php --filename "/home/it.audit/Host_Mib_Summary_Device.xml.gz"
ERROR: Invalid Argument: (/home/it.audit/Host_Mib_Summary_Device.xml.gz)

Or are you saying instead of "git clone" like I normally do I need to download the entire plugin as a zip, repackage it as a tar.gz and then run that command?

**Comment by hackdefendr** [comment]
Peter I got that too.... You have to put an equal sign after --filename.  Then it imports fine.

But something is still broken.  See Issue #7.

**Comment by peter-thoenen** [comment]
Thanks, I completely missed that.  Yes it's also listed in that way in the help, I just overlooked it assuming it took input like most standard unix commands (i.e. --command parameter)

**Comment by peter-thoenen** [comment]
GA and close this.  I will now figure out how to use git the first time in my life and do the above comment, i.e. not as easy as the good old "diff -ruN" submit ;)

**Comment by peter-thoenen** [comment]
Stupid question before you close this cigamit but how does one exactly create a pull request?  Pull Request->New Request is of no help.  Not a git guy

**Comment by cigamit** [comment]
Peter, YouTube can be your friend.  We welcome your contributions....

https://www.youtube.com/results?search_query=github+how+to+create+a+pull+request

**Comment by WirthmU** [comment]
I still get that "WARNING: You need to import your Host MIB Host Template to view Graphs. See the README for more information" issue.

I thought I would have done everything according to your installation description.

Any other things I might check?

**Comment by netniV** [comment]
```sql
SELECT 'htdq' AS NAME, (SELECT id FROM snmp_query WHERE HASH = '137aeab842986a76cf5bdef41b96c9a3' ) AS id
UNION
SELECT 'hcpudq' AS NAME, ( SELECT id FROM snmp_query WHERE HASH = '0d1ab53fe37487a5d0b9e1d3ee8c1d0d' ) AS id
UNION
SELECT 'hugt' AS NAME, ( SELECT id FROM graph_templates WHERE HASH = 'e8462bbe094e4e9e814d4e681671ea82' ) AS id
UNION
SELECT 'hpgt' AS NAME, ( SELECT id FROM graph_templates WHERE HASH = '62205afbd4066e5c4700338841e3901e' ) AS id
UNION
SELECT 'htsd' AS NAME, ( SELECT id FROM host_template WHERE HASH = '7c13344910097cc599f0d0485305361d' ) AS id
```
Run the above query.  We should add a section in the plugin that allows you to see this status and therefore know which are missing.  It's quite easy that you may have missed one but not realise it or which one.

**Comment by WirthmU** [comment]
Thank you very much for your quick reply!

I would need some help here. When you mean "run the above query". Would this be a mysql command querying the cacti database from outside cacti or using the data collection > data queries function within cacti?

Thank you for your support.

**Comment by netniV** [comment]
Use the MySQL or phpMyAdmin depending on what you have available and make sure you are in the cacti database.

**Comment by netniV** [comment]
Closing due to lack of response.
